In [2]:
import numpy as np
import pandas as pd

In [3]:
w=np.array([1,-1,0,0.5]).transpose()
Xi=[np.array([1,-2,1.5,0]).transpose(), np.array([1,-0.5,-2,-1.5]).
    transpose(), np.array([0,1,-1,1.5]).transpose()]
C=1
Iteration=0
print(w)
print (Xi) 
#print(len(xi))

[ 1.  -1.   0.   0.5]
[array([ 1. , -2. ,  1.5,  0. ]), array([ 1. , -0.5, -2. , -1.5]), array([ 0. ,  1. , -1. ,  1.5])]


In [6]:
for i in range(len(Xi)): 
    net=sum(w.transpose()*Xi[i])
    print(net)
    Fnet=np.sign(net)
    print(Fnet)
    dw=C*Fnet*Xi[i]
    print(dw)
    w=w+dw 
    print('weight vector for this iteration:',w)
    Iteration+=1

14.75
1.0
[ 1.  -2.   1.5  0. ]
weight vector for this iteration: [ 2.  -5.5  6.   0.5]
-8.0
-1.0
[-1.   0.5  2.   1.5]
weight vector for this iteration: [ 1. -5.  8.  2.]
-10.0
-1.0
[-0.  -1.   1.  -1.5]
weight vector for this iteration: [ 1.  -6.   9.   0.5]


In [5]:

print ("final weight matrix:",w) 
print('number of iterations: ', Iteration)

final weight matrix: [ 1.  -3.5  4.5  0.5]
number of iterations:  3


In [9]:
num_inputs = int(input("Enter the number of inputs: "))
num_samples = int(input("Enter the number of training samples: "))
train_set = [[int(input()) for x in range (num_inputs)] for y in range(num_samples)] 

C = float(input("Enter the value of learning constant: "))

# weights = [np.random.uniform(-1,1) for i in range(num_inputs)]
weights = [1,-1]

def sign_function(input_value):
  return (1 if input_value >= 0 else -1)

for iteration in range(len(train_set)):
  net_value = 0
  for i in range(len(weights)):
    net_value += weights[i] * train_set[iteration][i] 
  
  signed_value = sign_function(net_value)
  delta = [C*signed_value*x for x in train_set[iteration]]
  for j in range(len(weights)):
    weights[j] = weights[j] + delta[j]

print(weights)

Enter the number of inputs:  3
Enter the number of training samples:  4
 5
 6
 7
 8
 9
 4
 6
 5
 5
 5
 6
 7
Enter the value of learning constant:  1


[-23.0, -27.0]


In [1]:
import pandas as pd
import numpy as np

In [2]:
data_pheno=pd.read_csv(r'data_phenotypic.csv')

In [3]:
data_smri=pd.read_csv(r'imagefeatures.csv')

In [4]:
data_pheno.shape

(1100, 29)

In [5]:
data_smri.shape

(1101, 2050)

In [16]:
data_pheno.shape

(1100, 29)

In [8]:
data_smri.columns

Index(['SNO', 'subject', '0', '1', '2', '3', '4', '5', '6', '7',
       ...
       '2038', '2039', '2040', '2041', '2042', '2043', '2044', '2045', '2046',
       '2047'],
      dtype='object', length=2050)

In [10]:
new=pd.merge(data_pheno,data_smri, on='subject', how='inner')

In [11]:
new.shape

(1100, 2078)

In [12]:
new.to_csv('dataset1.csv')

In [14]:
new.drop('Unnamed: 0',axis=1,inplace=True)

In [15]:
new

DX_GROUP  DSM_IV_TR  subject  AGE_AT_SCAN  SEX     FIQ  \
0            1          1    50002        16.77    1   103.0   
1            1          1    50003        24.45    1   124.0   
2            1          1    50004        19.09    1   113.0   
3            1          1    50005        13.73    2   119.0   
4            1          1    50006        13.37    1   109.0   
...        ...        ...      ...          ...  ...     ...   
1095         1          2    51583        35.00    1 -9999.0   
1096         1          2    51584        49.00    1 -9999.0   
1097         1          1    51585        27.00    1 -9999.0   
1098         1          2    51606        29.00    2 -9999.0   
1099         1          2    51607        26.00    1 -9999.0   

      EYE_STATUS_AT_SCAN   anat_cnr  anat_efc  anat_fber  ...      2038  \
0                      2  10.201539  1.194664  16.223458  ...  0.709169   
1                      2   7.165701  1.126752  10.460008  ...  0.000000   
2                      2   7.698144  1.226218   9.725750  ...  0.000000   
3                      2   9.071807  1.256278  11.198226  ...  0.000000   
4                      2   8.026798  1.407166   6.282055  ...  0.000000   
...                  ...        ...       ...        ...  ...       ...   
1095                   2   3.899774  1.697271   3.465151  ...  2.027425   
1096                   2   2.757735  1.073076   7.633618  ...  1.784619   
1097                   2   3.413469  1.358238   4.335700  ...  0.542140   
1098                   2   7.839007  1.754363  12.270055  ...  2.010930   
1099                   2  12.169297  2.818352   9.272107  ...  0.000000   

           2039      2040      2041      2042      2043      2044      2045  \
0      0.145987  0.573981  1.079048  0.134220  6.668210  0.000000  1.752300   
1      0.341641  0.000000  3.089838  0.000000  1.457187  0.000000  0.387380   
2      1.229481  0.000000  2.499114  0.000000  2.882995  0.000000  0.116916   
3      3.199678  0.000000  4.286026  0.711807  0.000000  0.000000  1.928197   
4      1.352294  0.377805  0.707129  0.000000  4.792439  0.000000  1.056621   
...         ...       ...       ...       ...       ...       ...       ...   
1095  10.180809  0.000000  0.000000  0.000000  2.317079  0.000000  1.292755   
1096   6.494457  0.000000  2.521507  0.000000  0.000000  0.000000  1.361214   
1097   7.581014  0.000000  1.033106  0.000000  0.151174  0.000000  0.000000   
1098   0.000000  0.068670  0.000000  5.233705  6.228088  0.000000  0.871909   
1099   0.000000  0.000000  4.542171  1.996868  3.232938  0.581755  0.536283   

           2046      2047  
0     17.515268  5.955179  
1     23.950901  3.587801  
2     15.910932  7.955417  
3     14.744667  5.338909  
4     12.811856  2.673212  
...         ...       ...  
1095   7.126568  3.599783  
1096   5.367865  0.610961  
1097   7.463575  2.034858  
1098  13.715996  9.897217  
1099  17.962841  5.092534  

[1100 rows x 2077 columns]